Homework #1 PR
MiraiRatchet/Modern-CPP-Programming pull request #1
Opened 2023-03-27 16:27 UTC by MiraiRatchet

2023-04-02 10:51 UTC, Arugaf requested changes
Преподаватель не добавлен в репозиторий.

Никто не назначен в качестве ревьюера и assignee.

Нет личной информации и описания в описании к пр.

Нет смысла в названии пр.

Коммит, к большому сожалению, только один и не содержит вообще никакой семантической нагрузки. Надо все же стремиться к атомарности и информативности.

Не используются ни именованные, ни анонимные неймспейсы.

CI надо бы починить, конечно.

Нет запуска тестов, расчета покрытия, отчета. Нет сборки и запуска с санитайзерами.

Не хватает хорошего разделения блоков кода по смысловому признаку (отделяя пустой строкой).

Не хватает constexpr/noexcept/const спецификаторов и атрибутов там, где это необходимо.

Нужно нормальное разбитие на классы с соответствием принципам SOLID.

Очень много магических констант/хардкода. В целом ощущение, что код в значительной степени написан в си стайле.

Много неудачных названий переменных/функций/методов: сокращения, сложночитаемые названия, с плохой семантикой и т.п.

Пока 1/10.

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +          sudo apt-get install -y cppcheck
Почему бы тут (и далее) не использовать соответствующий action?

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +        run: clang-format --dry-run --Werror -style=file:./config/.clang-format ./src/*.cpp ./App/include/*.hpp ./App/src/*.cpp
Почему все файлы подаются вручную?

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +          cmake --build build
Толку от этой джобы, если ее результат никуда не передается?

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +          cmake --build build
Почему билдим заново?

Почему перегенерируем файлы сборки сразу же после генерации первых?

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +    needs: [ build ]
Почему clang-tidy зависит от build? Должно быть наоборот.

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +        # clang-tidy --config-file=./config/.clang-tidy ./tests/*.cpp -p build
Комментариев с нерабочим кодом быть не должно.

2023-04-02 10:51 UTC, Arugaf commented on .github/workflows/cigit.yml
> +#   sudo valgrind --leak-check=full -s ./build/tests/main_tests
?

2023-04-02 10:51 UTC, Arugaf commented on .gitignore
> +/.DS_Store
[gitignore.io](https://www.gitignore.io/)

2023-04-02 10:51 UTC, Arugaf commented on App/CMakeLists.txt
> +target_include_directories(App PUBLIC include)
Это все? Где использование переменных? Прочие команды?

2023-04-02 10:51 UTC, Arugaf commented on App/CMakeLists.txt
> +target_include_directories(App PUBLIC include)
Почему паблик?

2023-04-02 10:51 UTC, Arugaf commented on App/CMakeLists.txt
> +target_include_directories(App PUBLIC include)
В конце каждого файла должна быть ровно одна пустая строка.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +#pragma once
Пустая строка между копирайтом и `#pragma once`.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +// Copyright(c) 2023 Klimova Mary
А нужен ли он тут в принципе?

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +#include <memory>
Инклюды должны идти в алфавитном порядке.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +};
Чтобы проще было отделять названия структур/классов от полей, следует именовать первые в UpperCamelCase.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +};
Что эта структура делает в этом файле?

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +    std::string nameDirector;
directorId
directorName

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +    std::vector<std::string> knownForTitles;
Непонятно что за поле.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +    static int Run(int argc, char **argv);
Налеплено.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +                                 std::unique_ptr<directorInfo> const &dirInfo);
Чем обусловлен перенос?

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +        std::unique_ptr<directorInfo> const &dirInfo);
Неудачные названия аргументов (тут и везде).

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +        std::unique_ptr<directorInfo> const &dirInfo);
Передача unique_ptr по ссылке - зло.

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +        std::string nbasname, std::string director,
Почему копия?

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +                                 std::unique_ptr<directorInfo> const &dirInfo);
Почему этот класс вообще знает про бизнес логику?

2023-04-02 10:51 UTC, Arugaf commented on App/include/App.hpp
> +    static int Run(int argc, char **argv);
Почему везде-везде возвращается int?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    const int neededArgsNum = 6;
constexpr и в анонимный неймспейс.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +                                                    {"-dir", ""}};
Тоже в анонимный неймспейс. Подобные вещи в теле функции загрязняют ее и усложняют чтение.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +        return 2;
Магическая константаю

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    if (parseCmd(&arguments, argc, argv)) {
Почему передаем адрес вместо ссылки?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    std::unique_ptr<directorInfo> dirInfo = std::make_unique<directorInfo>();
`auto`

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    if (App::directorsInfoCheck(arguments["-nbasics"], arguments["-dir"],
Хардкод.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    return 0;
Слишком большая (в том смысле, что слишком много знающая и без конкретной зоны ответственности) и сложночитаемая функция.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    std::cout << std::endl;
Почему?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    return 0;
Нечитаемо.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    imdbnbas.open(nbasname);
Привязка к типу потока. Нехорошо.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +        std::cout << "Names database is not opened." << std::endl;
Почему эта функция знает про стандартный поток вывода?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +        std::cout << "Names database is not opened." << std::endl;
Was not opened?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    std::string line = "";
Явный вызов дефолтного конструктора?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    getline(imdbnbas, line);
Проверки на ошибки?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    imdbnbas.close();
RAII

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    int i = 0;
Почему объявление вне цикла?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    while (i < df->knownForTitles.size() && !imdbtbas.eof()) {
Стремимся к цели "No raw loops" там, где это возможно.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +int App::parseCmd(std::map<std::string, std::string> *arguments, int argc,
Почему указатель на мапу?

Почему вообще именно `std::map`, а не `std::unordered_map`?

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +}
По большому счету на все методы +- одинаковые замечания.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +        }
Стараемся не использовать else.

2023-04-02 10:51 UTC, Arugaf commented on App/src/App.cpp
> +    for (int i = 1; i < argc; i++) {
Префиксный инкремент/декремент >> постфиксного.

2023-04-02 10:51 UTC, Arugaf commented on CMakeLists.txt
> +target_link_libraries(${ProjectName} App)
Неконсистентность стиля.

Стоит больше поразбивать на логические блоки.

2023-04-02 10:51 UTC, Arugaf commented on CMakeLists.txt
> +add_executable(${ProjectName} src/imdbdataanalyze.cpp)
Где соответствующие переменные?

2023-04-02 10:51 UTC, Arugaf commented on CMakeLists.txt
> +target_link_libraries(${ProjectName} App)
Не хватает пустой строки в концу файла.

2023-04-02 10:51 UTC, Arugaf commented on src/imdbdataanalyze.cpp
> +    return 0;
`return App::Run(argc, argv);`

2023-04-02 10:51 UTC, Arugaf commented on tests/unittests.cpp
> +    EXPECT_EQ(App::parseCmd(&arguments, argc, argv), 1);
Юнит тесты ни о чем, конечно же. Нет интеграционных тестов.

2023-04-02 10:51 UTC, Arugaf commented on tests/unittests.cpp
> +    char **argv = new char *[argc];
Память потекла.

Неоправданное выделение сырой памяти.

2023-04-08 11:49 UTC, MiraiRatchet commented
Кажется, я что-то совсем намудрила и стало сильно хуже, но постаралась исправить большинство замечаний касаемо стиля кода. Запрашиваю повторное ревью.

2023-12-05 11:52 UTC, closed without merging